### ISSUE TITLE
KaTeX formula overlapping ToC on the right

### ISSUE THREAD

**Issue by Dr-Electron** [iota-community/iota-wiki#255]
**Describe the bug**
The formula in https://wiki.iota.org/IOTA-2.0-Research-Specifications/5.3%20Mana#5332-active-consensus-mana-and-epochs overlaps on the right.

**Screenshots**
<img width="1247" alt="Bildschirmfoto 2021-09-27 um 01 58 46" src="https://user-images.githubusercontent.com/61637085/134828784-f3477caa-bf38-48a8-984a-3203e5fcd165.png">

**Comment by jlvandenhout** [comment]
I see two options here:
1. Find a way to render math blocks similarly to how code blocks are rendered, having their own scroll container.
2. Report this to https://github.com/iotaledger/IOTA-2.0-Research-Specifications and have them rewrite that statement, because this is too long for any page anyway and easily shortened by defining that if statement elsewhere.
