### ISSUE TITLE
Navigation through the wiki.

### ISSUE THREAD

**Issue by aleksei-korolev** [iota-community/iota-wiki#39]
Currently, we imagine the wiki being split into five sections: LEARN, BUILD, PARTICIPATE, PRODUCTS, RESEARCH. BUILD/Developer Docs could easily include a dozen software projects that have a dozen articles each. In total, the wiki would consist of dozens of subsections and hundreds of articles. That's a lot to navigate through.

![](https://media.discordapp.net/attachments/845301151439781968/854642010932379648/Architecture_-_FINAL_Foundation.png?width=1216&height=889)

My suggestion would be to have top-level sections listed in the topbar like the programming language picker in [wc3schools](https://www.w3schools.com/python/default.asp). The user would switch between top-level sections by clicking on topbar. The sidebar would list TOC only of the current top-level section, but not the others.

This solution would split advanced developer's docu (BUILD section) from end user docu (all other sections). Having the rest four sections separated from each other in the same way means consistent UI as five buttons in the topbar would all do the same. It also reflects the structure: if we have "devs vs non-devs" switch, it would essentially bring a new layer to our document structure: DEV that only has BUILD section, and NON-DEV that has the other four.

Finally, I think this is not just about "dev vs non-dev". With RESEARCH section, it is also "academic vs non-academic", and with PARTICIPATE section, it is "engaged user vs casual user". I do not see that we need to separate docs for devs more than docs for any other major user group.

**Comment by AdamCroply** [comment]
I think it's important not to separate the entirety of the build section as high-level content. For example, the 'Getting Started' section would be introductions and basic outlines of functionality and features, or basic guides to introduce people to the eco-system. 

The high-level content is very much contained within the Developer Documents/Repos. It's not as black and white as that, as mentioned, but I think the majority of the wiki in it's current state is more geared towards information and opening doors to the more complex content such as dev docs, research papers, etc...

I love the idea of a top bar, but I think this could simply be used to handle the dev docs and the main wiki (rather than all the individual categories.)

**Comment by Phyloiota** [comment]
I would now call it fixed for the time being and we should do content on that agreed structure after the good input from everyone:
https://cdn.discordapp.com/attachments/845301151439781968/855106870213345330/Architecture_-_FINAL_Adam_Edit.png
