### ISSUE TITLE
Update yarn.lock on build

### ISSUE THREAD

**Issue by Dr-Electron** [iota-community/iota-wiki#558]
**Is your feature request related to a problem? Please describe.**

Right now if the external repo add for example a new dependency the wiki build would fail until we update yarn.lock

**Describe the solution you'd like**

I guess it would be nice if we would just allow changes to the yarn.lock.

**Comment by jlvandenhout** [comment]
I guess we have two options to somewhat automate this:

1. We could leave the workflow as is for now, because in the deploy action we leave out the `--immutable` flag, so Yarn is allowed to update the lock file in current builds. We control what submodules get updated automatically anyway, and those are under IF control. Pro: no maintenance required. Con: we need to rely on the submodules to properly check their dependencies, because we will have no checks on our side.
2. We could create an action that runs as a cron job every day, creating a PR when it notices the lock file would need to be mutated, notifying us. This would allow us to add back the `--immutable` flag to let the build fail until we merge the PR. Pro: no unchecked dependency changes, possibly even with a nice summary of changing dependencies. Con: manual step in between, but mitigated by the fact that it won't happen very often.

**Comment by Dr-Electron** [comment]
1

> I guess we have two options to somewhat automate this:
> 
> 1. We could leave the workflow as is for now, because in the deploy action we leave out the `--immutable` flag, so Yarn is allowed to update the lock file in current builds. We control what submodules get updated automatically anyway, and those are under IF control. Pro: no maintenance required. Con: we need to rely on the submodules to properly check their dependencies, because we will have no checks on our side.
> 2. We could create an action that runs as a cron job every day, creating a PR when it notices the lock file would need to be mutated, notifying us. This would allow us to add back the `--immutable` flag to let the build fail until we merge the PR. Pro: no unchecked dependency changes, possibly even with a nice summary of changing dependencies. Con: manual step in between, but mitigated by the fact that it won't happen very often and we can add often used dependencies to the "default list of dependencies" of the Wiki.

Be careful. I think point one is not true. Just try it out on your fork. I think giithub related pages force something here. Because our build system already broke once although we never had the --immutable flag

**Comment by Dr-Electron** [comment]
Makes sense 👍

**Comment by jlvandenhout** [comment]
Resolved by #569.
