### ISSUE TITLE
Remove Tutorials and Ho-Tos from the docs

### ISSUE THREAD

**Issue by Dr-Electron** [iota-community/iota-wiki#583]
**Is your feature request related to a problem? Please describe.**

Right now we duplicate the tutorials in the docs and in the tutorial section. 

**Describe the solution you'd like**

In the future we should only add a link in the tutorials with a query link for tutorials.

Examples:
https://wiki.iota.org/tutorials?tags=identity&tags=how-to
https://wiki.iota.org/tutorials?tags=identity&tags=tutorials

**Comment by jlvandenhout** [comment]
So my opinion is to only remove tutorials from the sidebar and replace them with a link that automatically selects the project tag to filter tutorials on the tutorial page like Kevin suggests. I'd keep the how-to's in the sidebar of the project.

Just to be sure others understand: this is just about how to structure the client side. On the repository side, nothing has to change, we can keep both tutorials and how-tos in the associated project documentation directory.

**Comment by Dr-Electron** [comment]
Thanks for clarifying. Should have made that more clear 👍

**Comment by Dr-Electron** [comment]
Wait... Why would you keep the how-to's?

**Comment by jlvandenhout** [comment]
I'd like to adhere to the Diataxis definitions, and in that case I think it makes more sense to keep how-tos together with a project. It's never "how to run a node", it's "how to install a Hornet node on Linux", "how to configure a Bee node", "how to update and restart your Wasp node", very specific and related to a single project. Tutorials on the other hand would be "Create a payed data stream using DID, Streams and wallet.rs", it involves more projects and as such would live in the tutorial section and each project would link to the tutorial section with its own tag as filter, which will show related tutorials.

**Comment by jlvandenhout** [comment]
@lucas-tortora @aleksei-korolev we need your verdict here.

**Comment by lucas-tortora** [comment]
> @lucas-tortora @aleksei-korolev we need your verdict here.

Separating the how-tos from the projects doesn't seem to make sense to me. They are always strictly tied to the code base and bound to get outdated if we separate the two.  Additionally, it'd be a nightmare to maintain as in many cases the actual code snippets are imported from the project's code-base.  That being said, it'd probably be nice to import and list them if it's not too much work as in many cases they'd be a good substitute for a full-length tutorial until we have one.  

Regarding tutorials, I think we possibly have the best of both worlds by cross-referencing.  If a tutorial belongs 100% to a single project (for example, `validate university degree` in Identity) it makes sense to keep the MD file within the project so it can be updated as the project evolves.   If the tutorial uses multiple projects the answer to this question is a bit blurrier.  However, I think can possibly work around this by:

1) Importing anything within a `tutorial` folder in any project to the tutorials section, and tagging it accordingly (project name, tutorial title, language - all these could be retrieved from metatags).  Since we don't have many nowadays, perhaps creating an importer is overkill for the time being. 

2) Removing the actual tutorials from the sidebar and replacing them with a `Tutorials` link, which would lead the user to the Tutorials section with this project selected as a filter.  

This way we'd keep tutorials tied to their codebase where it makes sense to do so, they'd be included in the codebase for the off case that someone is using a DLT without internet, and they'd all be added to the tutorials section for any users browsing tutorials, and we divert traffic to the tutorials section from within the project and vice-versa if we add good reference links to the tutorials.  

Wdyt?

**Comment by jlvandenhout** [comment]
> Separating the how-tos from the projects doesn't seem to make sense to me. They are always strictly tied to the code base and bound to get outdated if we separate the two. Additionally, it'd be a nightmare to maintain as in many cases the actual code snippets are imported from the project's code-base. That being said, it'd probably be nice to import and list them if it's not too much work as in many cases they'd be a good substitute for a full-length tutorial until we have one.

As stated above, we are purely talking about the placement in the Wiki, not about where to put the source. How-to sources should remain in their associated code bases. Tutorials can be too if deemed appropriate, it doesn't matter where they are located like you say.

This issue is about where we place how-to's and tutorials in the Wiki. Kevin suggests to remove both how-to's and tutorials from the project sidebars and move them to the tutorial page and then just link to the tutorial page from the project sidebars with a appropriate tag queries so you get all how-to's and tutorials associated to the project you navigated from.

I fully agree moving tutorials to the tutorial page and only place a link to the tutorial page in the sidebar of projects. I disagree on removing the how-to's and mixing them with tutorials though, because as you said they are strictly tied to the project and imho should remain in the sidebar of the associated project. In my mind the tutorial page is for tutorials only, not for how-to's.

**Comment by lucas-tortora** [comment]
> > this tutorial`or`How to guides that match your search criteria`:
> > How to set up a Bee node with Docker
> > [...]
> 
> So you basically agree on "moving" the tutorials, did I get this right? The tutorials are still part of the repo but in the sidebar we just link to the tutorial section with the correct queries and the tutorial section will query the tutorials from the repo basically.
> 
> Now that we agree on that one. I disagree with @jlvandenhout :trollface: I think how-to's should be part of the tutorial section. Didn't we create this section because we said we need something like `how-to send iota` somewhere? Getting started tutorials? Which are basically how-to's, no?

Yup, that's about it.  And for how-tos, it'd be the same query, except that the results would lead the user to the project for the reasons you're stating.  We may not have a full-blown tutorial that explains what a DLT, nodes and wallet are and how you can use them to send and receive transactions. But we do have a nice how to on using wallet to send iota to another account, another on running a Hornet Node and this article which explains what IOTA is and how it realtes to other dlts.  Basically related how-tos and explanations in related to the user's search query.

**Comment by jlvandenhout** [comment]
> But we do have a nice how to on using wallet to send iota to another account, another on running a Hornet Node and this article which explains what IOTA is and how it realtes to other dlts. Basically related how-tos and explanations in related to the user's search query.

But where do we place the how-to's in your opinion? As in, what is their main entrypoint?

1. *The project sidebar*: We have a `how-to's` subsection in the sidebar of the project, listing all how-to's. We could then link to them from the Tutorials section using either cards (which requires configuration) or links (my preference, creates a clear distinction between actual tutorials and how-to's being linked to).
2. *The tutorial section*: We have how-to's mixed with tutorials in the tutorial section (either as cards or as links), and instead of the `how-to's` subsection we just have a link in the project sidebar that targets the tutorial section with a query to filter on the project and `how-to` type, just like the tutorial link that would filter `tutorial` type.

I prefer 1.

**Comment by lucas-tortora** [comment]
> 1. have a `how-to's` subsection in the sidebar of the project, listing all how-to's. We could then link to them from the tutorials section using either cards (which requires metadata configuration like a card image and description) or links (my preference, creates a clear distinction between actual tutorials and how-to's being linked to).

I say we go with 1.  We can revaluate when we have some user experience data, wdyt?

**Comment by jlvandenhout** [comment]
@Dr-Electron I guess we could use markdown frontmatter tags for this? We can extend the tutorials section logic to also list any how-to's tagged with certain topics.

**Comment by Dr-Electron** [comment]
> @Dr-Electron how tos are actually closer to references than tutorials because they are basically a handbook for a professional to quickly look up some conrete question on a concrete task at hand, and I would then prefer to have my whole "handbook" in one place rather than spit between the project space and the general IOTA tutorials page, albeit with filters. "How to send iota" should be a tutorial.
> 
> See https://diataxis.fr/tutorials-how-to/#tutorials-how-to

Guess I'm too stupid to get the difference. I will get it with time. I hope 😅 

If `How to run a node` and `How to send IOTAs with the cli-wallet` isn't a how-to but a tutorial I'm fine with just linking to the tutorial section for tutorials.

I'm still not sure if we all are on the same point of understanding what we want to do.

So let's do the following:
We do it for tutorials and discuss this again once that Is live. Fine for everyone? 😅

**Comment by Dr-Electron** [comment]
> > @Dr-Electron I guess we could use markdown frontmatter tags for this? We can extend the tutorials section logic to also list any how-to's tagged with certain topics.
> 
> I don't know if it helps, but just in case it does, we're moving all the how-tos in each project in a folder called `how_tos` at the root of `docs`, perhaps it's easier to just crawl through the folder.

That is a possibility, yes. In the end we can just query front matter with the plugin tho.
We have an open issue for that https://github.com/iota-wiki/plugin-tutorial/issues/1

**Comment by aleksei-korolev** [comment]
Tutorial as a curated experience to learn how to interact with a product. There is only one happy path, nothing can go wrong. In "sending your first transaction" you would make sure that the user joins to the test network, requests necessary tokens from the faucet, sets two wallets and sends money from one wallet to another.

"How to" is a guide for a real world application. "You send your tokens like this, if you get this error then you don't have enough balance, if this error then you lost connection to a node, if this error you had hit the dust protection". We can't control the user environment and we don't know the user environment, but we can guess potential scenarios and try to cover them.

Tutorials are a great streamlined learning experience. How tos are great for troubleshooting tasks that you already working on
